---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jdna-sync-test
  namespace: argocd
  labels:
    app: jdna-sync-test
    env: test
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - list:
        elements:
          - "banner": "dtlr"
          - "banner": "nk"
          - "banner": "spc"
          
  template:
    metadata:
      name: 'jdna-sync-{{ .banner }}-test'
      labels:
        app: 'jdna-sync-{{ .banner }}-test'
        env: test
    spec:
      project: jdna-sync
      destination:
        namespace: jdna-sync
        name: aks-northcentralus-c9d54b825de9
      sources:
        - repoURL: https://github.com/dtlr/jdna-sync.git
          targetRevision: qa
          path: argo-app
          kustomize:
            namespace: jdna-sync
            commonLabels:
              app: 'jdna-sync-{{ .banner }}-test'
              env: test
              banner: '{{ .banner }}'
            images:
              - ghcr.io/dtlr/jdna-sync:sha-4b72b1c
            patches:
              - patch: |
                  - op: replace
                    path: /metadata/name
                    value: 'jdna-sync-{{ .banner }}-test'
                target:
                  kind: Service
                  name: svc
              - patch: |
                  - op: replace
                    path: /spec/selector/app
                    value: 'jdna-sync-{{ .banner }}-test'
                target:
                  kind: Service
                  name: svc
              - patch: |
                  - op: replace
                    path: /metadata/name
                    value: 'jdna-sync-{{ .banner }}-test'
                target:
                  kind: Deployment
                  name: appDeployment
              - patch: |
                  - op: replace
                    path: /spec/selector/matchLabels/app
                    value: 'jdna-sync-{{ .banner }}-test'
                target:
                  kind: Deployment
                  name: appDeployment
              - patch: |
                  - op: replace
                    path: /spec/template/spec/containers/0/name
                    value: 'jdna-sync-{{ .banner }}-test'
                target:
                  kind: Deployment
                  name: appDeployment
              - patch: |
                  - op: replace
                    path: /spec/template/spec/containers/0/env/3/value
                    value: debug
                target:
                  kind: Deployment
                  name: appDeployment
              - patch: |
                  - op: replace
                    path: /spec/template/spec/containers/0/env/5/name
                    value: '{{ upper .banner }}_DATABASE_URI'
                target:
                  kind: Deployment
                  name: appDeployment
              - patch: |
                  - op: replace
                    path: /spec/rules/0/host
                    value: 'jdna-sync-{{ .banner }}.test.jdna.io'
                target:
                  kind: Ingress
                  name: appIngress
              - patch: |
                  - op: replace
                    path: /spec/tls/0/hosts/0
                    value: 'jdna-sync-{{ .banner }}.test.jdna.io'
                target:
                  kind: Ingress
                  name: appIngress
              - patch: |
                  - op: replace
                    path: /spec/tls/0/secretName
                    value: 'jdna-sync-{{ .banner }}-test-tls'
                target:
                  kind: Ingress
                  name: appIngress
              - patch: |
                  - op: replace
                    path: /metadata/name
                    value: 'sync-stores-{{ .banner }}-test'
                target:
                  kind: CronJob
                  name: appSyncStoresCronJob
              - patch: |
                  - op: replace
                    path: /spec/template/spec/containers/0/name
                    value: 'sync-stores-{{ .banner }}-test'
                target:
                  kind: CronJob
                  name: appSyncStoresCronJob
              - patch: |
                  - op: replace
                    path: /spec/template/spec/containers/0/env/8/name
                    value: '{{ upper .banner }}_DATABASE_URI'
                target:
                  kind: CronJob
                  name: appSyncStoresCronJob
              - patch: |
                  - op: replace
                    path: /spec/template/spec/containers/0/env/8/valueFrom/secretKeyRef/key
                    value: '{{ upper .banner }}_DATABASE_URI'
                target:
                  kind: CronJob
                  name: appSyncStoresCronJob
              - patch: |
                  - op: replace
                    path: /metadata/name
                    value: 'sync-terminals-{{ .banner }}-test'
                target:
                  kind: CronJob
                  name: appSyncTerminalsCronJob
              - patch: |
                  - op: replace
                    path: /spec/template/spec/containers/0/name
                    value: 'sync-terminals-{{ .banner }}-test'
                target:
                  kind: CronJob
                  name: appSyncTerminalsCronJob
              - patch: |
                  - op: replace
                    path: /spec/template/spec/containers/0/env/8/name
                    value: '{{ upper .banner }}_DATABASE_URI'
                target:
                  kind: CronJob
                  name: appSyncTerminalsCronJob
              - patch: |
                  - op: replace
                    path: /spec/template/spec/containers/0/env/8/valueFrom/secretKeyRef/key
                    value: '{{ upper .banner }}_DATABASE_URI'
                target:
                  kind: CronJob
                  name: appSyncTerminalsCronJob

        - repoURL: https://github.com/dtlr/jdna-sync.git
          targetRevision: qa
          path: argo-app-secret
          kustomize:
            namespace: jdna-sync
            commonLabels:
              env: test
              banner: '{{ .banner }}'
            patches:
              - patch: |
                  - op: replace
                    path: /metadata/name
                    value: app-secret-test
                target:
                  kind: ExternalSecret
                  name: app-secret
              - patch: |
                  - op: replace
                    path: /spec/target/name
                    value: app-secret-test
                target:
                  kind: ExternalSecret
                  name: app-secret
              - patch: |
                  - op: app
                    path: /spec/data/0/secretKey/remoteRef/property
                    value: credential-test
                target:
                  kind: ExternalSecret
                  name: app-secret
              - patch: |
                  - op: app
                    path: /spec/data/8/secretKey
                    value: '{{ upper .banner }}_DATABASE_URI'
                target:
                  kind: ExternalSecret
                  name: app-secret
              - patch: |
                  - op: app
                    path: /spec/data/8/remoteRef/key
                    value: 'jdna-sync-{{ .banner }}-test'
                target:
                  kind: ExternalSecret
                  name: app-secret
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=foreground
          - PruneLast=true
          - RespectIgnoreDifferences=true
        automated:
          prune: true
          selfHeal: true
