CREATE TABLE IF NOT EXISTS "stores" (
	"id" uuid PRIMARY KEY NOT NULL,
	"code" varchar(255) NOT NULL,
	"aptos_store_code" varchar(255) NOT NULL,
	"banner" varchar(24) NOT NULL,
	"name" varchar(255) NOT NULL,
	"short_name" varchar(255),
	"status" boolean DEFAULT false NOT NULL,
	"district" varchar(255),
	"region" varchar(255),
	"address_city" varchar(255),
	"address_email" varchar(255),
	"address_line1" varchar(255),
	"address_line2" varchar(255),
	"address_name" varchar(255),
	"address_state" varchar(255),
	"address_zip_code" varchar(255),
	"latitude" real,
	"longitude" real,
	"adyen_merchant_id" varchar(255),
	"adyen_id" varchar(255),
	"adyen_reference" varchar(255),
	"adyen_status" varchar(255),
	"adyen_description" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"deleted_at" timestamp,
	CONSTRAINT "stores_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "terminals" (
	"id" uuid PRIMARY KEY NOT NULL,
	"company_id" varchar(255) NOT NULL,
	"merchant_id" varchar(255) NOT NULL,
	"adyen_store_id" varchar(255) NOT NULL,
	"store_id" uuid NOT NULL,
	"name" varchar(255),
	"model" varchar(255),
	"serial_number" varchar(255),
	"firmware_version" varchar(255),
	"cellular_iccid" varchar(255),
	"wifi_ip_address" varchar(255),
	"wifi_mac_address" varchar(255),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp,
	"deleted_at" timestamp
);
