---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret-banner
spec:
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: app-secret-banner
    creationPolicy: Owner
  data:
    - secretKey: APP_NEON_DATABASE_URI
      remoteRef:
        key: jmc-pgsql-jmc-jm
        property: connection_string
