apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appName
  template:
    spec:
      containers:
        - name: jdna-sync
          image: ghcr.io/dtlr/jdna-sync:edge
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/app.env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/app.service']
            - name: APP_PORT
              value: '3000'
            - name: LOG_LEVEL
              value: 'debug'
            - name: APP_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['env']
            - name: APP_NEON_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: app-secret-banner
                  key: APP_NEON_DATABASE_URI
            - name: APP_BANNER
              value: some-value
            - name: APP_BANNER_MERCHANT_ID
              value: some-value
            - name: LOCATIONSAPI_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret-common
                  key: LOCATIONSAPI_URL
            - name: LOCATIONSAPI_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret-common
                  key: LOCATIONSAPI_CLIENT_ID
            - name: LOCATIONSAPI_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret-common
                  key: LOCATIONSAPI_CLIENT_SECRET
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: app-secret-common
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret-common
                  key: DB_PASSWORD
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: app-secret-common
                  key: DB_PORT
            - name: ADYEN_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret-common
                  key: ADYEN_KEY
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /v2/readyz
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
