---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secret
spec:
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: adyen-sync-secrets
    creationPolicy: Owner
  data:
    - secretKey: ADYEN_KEY
      remoteRef:
        key: adyen-worker
        property: credential
    - secretKey: DB_HOST
      remoteRef:
        key: jmc-pgsql-jmc-jm
        property: alias
    - secretKey: DB_USER
      remoteRef:
        key: jmc-pgsql-jmc-jm
        property: username
    - secretKey: DB_PASSWORD
      remoteRef:
        key: jmc-pgsql-jmc-jm
        property: password
    - secretKey: DB_PORT
      remoteRef:
        key: jmc-pgsql-jmc-jm
        property: port
    - secretKey: DTLR_DATABASE_URI
      remoteRef:
        key: jdna-sync
        property: connection_string
    - secretKey: SPC_DATABASE_URI
      remoteRef:
        key: jdna-sync
        property: connection_string
    - secretKey: LOCATIONSAPI_URL
      remoteRef:
        key: jfprocessor
        property: port
    - secretKey: LOCATIONSAPI_CLIENT_ID
      remoteRef:
        key: jfprocessor
        property: connection_string
    - secretKey: LOCATIONSAPI_CLIENT_SECRET
      remoteRef:
        key: jfprocessor
        property: connection_string
