apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - app-secret.yaml
  - pull-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sync-stores.yaml
  - sync-terminals.yaml

labels:
  - pairs:
      tags.datadoghq.com/jdna-sync.service: jdna-sync
    includeTemplates: true
