---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: jdna-pull-secret #this name will also be used for naming the generated kubernetes secret
type: kubernetes.io/dockerconfigjson
spec:
  itemPath: "vaults/Engineering/items/dtlr-jm-pullsecret"
