apiVersion: batch/v1
kind: CronJob
metadata:
  name: adyen-sync-terminals
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: adyen-sync-job
            tags.datadoghq.com/adyen-sync-terminals.env: qa
            tags.datadoghq.com/adyen-sync-job.service: adyen-sync-terminals
        spec:
          restartPolicy: Never
          containers:
            - name: adyen-sync-terminals
              image: ghcr.io/dtlr/adyen-sync:edge
              imagePullPolicy: Always
              command: ["./app/bin/run.js"]
              args: ["sync", "terminals"]
              env:
                - name: DD_ENV
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['tags.datadoghq.com/adyen-sync-terminals.env']
                - name: DD_SERVICE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['tags.datadoghq.com/adyen-sync-job.service']
                - name: APP_ENV
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['env']
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: adyen-sync-secrets
                      key: DB_USER
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: adyen-sync-secrets
                      key: DB_PASSWORD
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: adyen-sync-secrets
                      key: DB_HOST
                - name: DB_PORT
                  valueFrom:
                    secretKeyRef:
                      name: adyen-sync-secrets
                      key: DB_PORT
                - name: ADYEN_KEY
                  valueFrom:
                    secretKeyRef:
                      name: adyen-sync-secrets
                      key: ADYEN_KEY
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m 